services:
  - type: web
    name: histudy-laravel
    env: docker
    dockerfilePath: ./Dockerfile.nginx
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://webinnovate.dev
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: sqlite
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: QUEUE_CONNECTION
        value: sync
